### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by kslstn** [grimmer0125/markdown-preview-kramdown#7]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
For no apparent reason, the package can't install—even when it was installed before. I've updated macOS, XCode and Atom.

```
Installing “markdown-preview-kramdown@0.6.1” failed.Hide output…

> oniguruma@7.2.1 install /private/var/folders/m5/4cszbc8n2gz53r4jl20xk7z80000gn/T/apm-install-dir-2020427-21243-q8zks8.7jbtf/node_modules/markdown-preview-kramdown/node_modules/oniguruma
> node-gyp rebuild


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/m5/4cszbc8n2gz53r4jl20xk7z80000gn/T/apm-install-dir-2020427-21243-q8zks8.7jbtf/node_modules/markdown-preview-kramdown/node_modules/oniguruma
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/m5/4cszbc8n2gz53r4jl20xk7z80000gn/T/apm-install-dir-2020427-21243-q8zks8.7jbtf/package.json'
npm WARN apm-install-dir-2020427-21243-q8zks8.7jbtf No description
npm WARN apm-install-dir-2020427-21243-q8zks8.7jbtf No repository field.
npm WARN apm-install-dir-2020427-21243-q8zks8.7jbtf No README data
npm WARN apm-install-dir-2020427-21243-q8zks8.7jbtf No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@7.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@7.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/koos/.atom/.apm/_logs/2020-05-27T11_55_11_302Z-debug.log
```

### Steps to Reproduce

1. Install the package

or

1. Start Atom with the package installed

**Comment by bertolinocastro** [comment]
I'm having the same trouble. This repo isn't maintained since 2018. Maybe it won't be solved...
